### ISSUE TITLE
Errors running the bash script

### ISSUE THREAD

**Issue by PhilPalmer** [cgpu/staries#2]
There were two issues with running the bash script which could be resolved by the following:
1. Run the script from the home directory within the instance
2. Remove the `--allow-chan` from [here](https://github.com/cgpu/cloudies/blob/master/aws/ami-scripts/ubuntu_1804_docker_singularity_ami_34435ede.sh#L7)

**Comment by cgpu** [comment]
Thanks for the heads up, this commit fixes it https://github.com/cgpu/staries/commit/2696d663e985d460b65e7c0dff43d184ed09e3d5.
